## FILE: docker-compose.yml 

version: "2"
services:
  ndb_mgmd1:
    hostname: ndb_mgmd1
    container_name: ndb_mgmd1
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.1
    volumes:
      - ./volumes/ndb_mgmd1:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh ndb_mgmd 
  
  ndb_mgmd2:
    hostname: ndb_mgmd2
    container_name: ndb_mgmd2
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.2
    volumes:
      - ./volumes/ndb_mgmd2:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh ndb_mgmd 
  
  ndbd1:
    hostname: ndbd1
    container_name: ndbd1
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.11
    volumes:
      - ./volumes/ndbd1:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh ndbd 
  
  ndbd2:
    hostname: ndbd2
    container_name: ndbd2
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.12
    volumes:
      - ./volumes/ndbd2:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh ndbd 
  
  mysqld1:
    hostname: mysqld1
    container_name: mysqld1
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.21
    volumes:
      - ./volumes/mysqld1:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh mysqld 
  
  mysqld2:
    hostname: mysqld2
    container_name: mysqld2
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.22
    volumes:
      - ./volumes/mysqld2:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh mysqld 
  
  client:
    hostname: client
    container_name: client
    build: .
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 172.31.0.101
    volumes:
      - ./volumes/client:/var/lib/mysql-cluster
      - ./volumes/common:/var/lib/mysql-cluster/common
    entrypoint: /var/lib/mysql-cluster/common/entry.sh client 

networks:
  backend:
    driver: bridge
    ipam: 
      config:
      - subnet:   172.31.0.0/24
        gateway:  172.31.0.254
